### ISSUE TITLE
Only few apps are showing in Android 11

### ISSUE THREAD

**Issue by ealap** [arter97/AutoHzPerm#1]
I recently did a clean install of the 3rd Oxygen OS developer preview for OnePlus 8 based on Android 11 and AutoHz is only showing a few apps. The number of apps shown would also vary more or less for every refresh of the app view.

**Comment by arter97** [comment]
Beta releases are not supported.

**Comment by famewolf** [comment]
I'm on the official oxygen os Android 11 release. I had several issues that I finally nailed down to Autohz where the screen was going black and only a reboot would get me back. Holding down the power button I could feel it vibrate as if it was showing me the reboot menu but nothing was visible. The problem went away when I uninstalled Autohz. I can only guess it's having issues switching between 60 and 90 HZ.
