### ISSUE TITLE
Support Galaxy S21 (pro)

### ISSUE THREAD

**Issue by lunim** [arter97/AutoHzPerm#3]
The app closes on the S21 indicating the device is not supported.

**Comment by arter97** [comment]
Please read the description thoroughly. Only Galaxy S20 series are supported.

**Comment by lunim** [comment]
Hello,

Thanks for the reply.  I read the description and am aware the S21 is not currently supported.  I filed this to request S21 support be added if possible.

**Comment by arter97** [comment]
Sorry for the late reply.

Why would you be interested in running this in S21 though?
It has proper VRR support already.

**Comment by lunim** [comment]
> Sorry for the late reply.
> 
> Why would you be interested in running this in S21 though?
> It has proper VRR support already.

I've noticed a few apps seem blurry when scrolling, and was wanting to check if setting the frame rate manually would resolve the issue.

Thanks!
