### ISSUE TITLE
Suggest a simple way to open cmd.

### ISSUE THREAD

**Issue by Kamilake** [arter97/AutoHzPerm#4]
I found a new way to open cmd.
Hope this can help.

![image](https://user-images.githubusercontent.com/15166740/110408344-bb5a3d80-80c8-11eb-8e06-7eed3ef8ebd7.png)
![image](https://user-images.githubusercontent.com/15166740/110408378-c745ff80-80c8-11eb-9189-7dc6302ed1d1.png)
![image](https://user-images.githubusercontent.com/15166740/110408605-33c0fe80-80c9-11eb-8f40-88d532f18909.png)

**Comment by arter97** [comment]
Eh, I personally think both methods are equally easy. Not worth enough for me to reinstall English version of Windows to capture the screenshots again.
