### ISSUE TITLE
GM1917 AutoHz says Unsupported Device.

### ISSUE THREAD

**Issue by famewolf** [arter97/AutoHzPerm#5]
I have the 12/256GB version of the international unlocked, rooted with magisk and running the custom android 11 rom Derpfest from Xda-developer.com.   I have autohz working fine on two GM1915 (T-mobile) models that were modded to use international firmware before the custom rom however when the app was restored by google as part of the "copy from old device" it says the device is not supported and uninstalling will get me a refund which is not what I want.  

Let me know what you want to see.

**Comment by famewolf** [comment]
I backed up the app on the gm1915 via swift backup to cloud then restored on the gm1917 and it bypassed the issue by restoring the data but it's still something you should fix.

**Comment by arter97** [comment]
As mentioned in the app's description:
"AutoHz only works on devices running unmodified OS."

I have no intention of adding support for custom ROMs.
If your custom ROM is based on AOSP, it will not work despite bypassing the initial detection.
