### ISSUE TITLE
oneplus nord 2 is supported?

### ISSUE THREAD

**Issue by riosaas** [arter97/AutoHzPerm#8]
hello, I have a oneplus nord 2.... and before buying autohz I wanted to know if it was supported ..... Thank you

**Comment by ibLeDy** [comment]
I have the OnePlus Nord 2 5G. Nothing seems to work. Bought this app just today. Going to keep testing one or two days more before I ask for a refund tho...

I have disabled the permission monitoring setting, and granted the permission to the app. Enabling "show refresh rate" option confirms that the app has no effect for me.

Am I missing something?

**Comment by arter97** [comment]
This GitHub repository is not for providing support.

Please contact me via email in case of an inquiry.

To quickly answer your question, Nord 2's support is indeed less ideal than other OxygenOS-based devices.
I'm actively trying to figure out a solution, but meanwhile, to see if the app is actually working, the quickest way to check it is to set a browser app to 60. It should be noticeable right away if you scroll on the browser.

If it's not working under the browser as well, a simple reboot will fix the problem.
Android's Accessibility services seem to misbehave occasionally (especially right after the first installation) and reboot fixes it.
